models:
  - type: main
    engine: openai
    model: openai/gpt-4o-mini    
    parameters:
      base_url: "https://models.github.ai/inference"
rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output